import { ScreenTemplate, UIComponent } from "@/types";
import { generateId } from "@/lib/utils";

function makeComp(type: string, props: Record<string, unknown>, y: number, w = 240, h = 44): UIComponent {
  return { id: generateId(), type: type as any, props, x: 16, y, width: w, height: h, styles: {} };
}

export const SCREEN_TEMPLATES: ScreenTemplate[] = [
  // ── AUTH ──────────────────────────────────────────────────────────────────
  { id: "tpl_login_basic", name: "Basic Login", category: "Auth", description: "Email + password login with logo header", thumbnail: "🔐", framework: "both", tags: ["login", "auth", "email"],
    components: [makeComp("TextView", { text: "Welcome Back", textSize: "24sp", bold: true }, 24, 240, 36), makeComp("TextView", { text: "Sign in to continue", textSize: "14sp" }, 68, 240, 24), makeComp("EditText", { hint: "Email address", inputType: "textEmailAddress" }, 108, 240, 52), makeComp("EditText", { hint: "Password", inputType: "textPassword" }, 172, 240, 52), makeComp("Button", { text: "Sign In" }, 240, 240, 48), makeComp("TextView", { text: "Forgot Password?" }, 300, 240, 24)] },
  { id: "tpl_login_social", name: "Social Login", category: "Auth", description: "Login with Google, Facebook buttons", thumbnail: "🌐", framework: "both", tags: ["login", "social", "google"],
    components: [makeComp("ImageView", { src: "app_logo" }, 24, 80, 80), makeComp("TextView", { text: "eSmart World", textSize: "22sp", bold: true }, 116, 240, 32), makeComp("Button", { text: "Continue with Google", icon: "ic_google" }, 164, 240, 48), makeComp("Button", { text: "Continue with Email" }, 380, 240, 48)] },
  { id: "tpl_register", name: "Registration", category: "Auth", description: "Full registration form with validation", thumbnail: "📝", framework: "both", tags: ["register", "signup", "form"],
    components: [makeComp("TextView", { text: "Create Account", textSize: "24sp", bold: true }, 24, 240, 36), makeComp("EditText", { hint: "Full Name" }, 72, 240, 52), makeComp("EditText", { hint: "Email Address" }, 136, 240, 52), makeComp("EditText", { hint: "Phone Number", inputType: "phone" }, 200, 240, 52), makeComp("EditText", { hint: "Password" }, 264, 240, 52), makeComp("CheckBox", { text: "I agree to Terms & Privacy Policy" }, 328, 240, 32), makeComp("Button", { text: "Create Account" }, 376, 240, 48)] },
  { id: "tpl_otp", name: "OTP Verification", category: "Auth", description: "6-digit OTP code entry screen", thumbnail: "🔢", framework: "both", tags: ["otp", "verification", "code"],
    components: [makeComp("TextView", { text: "Verify Phone", textSize: "24sp", bold: true }, 40, 240, 36), makeComp("TextView", { text: "Enter the 6-digit code" }, 84, 240, 40), makeComp("EditText", { hint: "· · · · · ·", maxLength: "6" }, 148, 240, 64), makeComp("Button", { text: "Verify Code" }, 228, 240, 48)] },
  { id: "tpl_forgot_password", name: "Forgot Password", category: "Auth", description: "Password reset via email flow", thumbnail: "🔑", framework: "both", tags: ["forgot", "reset", "password"],
    components: [makeComp("TextView", { text: "Reset Password", textSize: "24sp", bold: true }, 40, 240, 36), makeComp("EditText", { hint: "Email Address" }, 140, 240, 52), makeComp("Button", { text: "Send Reset Link" }, 208, 240, 48), makeComp("Button", { text: "Back to Login" }, 268, 240, 40)] },
  { id: "tpl_biometric", name: "Biometric Login", category: "Auth", description: "Fingerprint / Face ID login screen", thumbnail: "🔏", framework: "android", tags: ["biometric", "fingerprint", "security"],
    components: [makeComp("ImageView", { src: "fingerprint_icon", height: "120dp" }, 80, 120, 120), makeComp("TextView", { text: "Touch Sensor to Login", textSize: "18sp", bold: true, textAlign: "center" }, 216, 240, 32), makeComp("TextView", { text: "Use your fingerprint for quick access", textAlign: "center" }, 256, 240, 32), makeComp("Button", { text: "Use Password Instead" }, 340, 240, 48)] },
  { id: "tpl_pin_lock", name: "PIN Lock Screen", category: "Auth", description: "4-digit PIN entry with keypad", thumbnail: "🔒", framework: "both", tags: ["pin", "security", "lock"],
    components: [makeComp("TextView", { text: "Enter PIN", textSize: "22sp", bold: true, textAlign: "center" }, 60, 240, 36), makeComp("CardView", { showDots: "4", dotSize: "16dp" }, 108, 200, 40), makeComp("CardView", { title: "Numpad", rows: "4", cols: "3", showDelete: "true" }, 160, 260, 300)] },

  // ── DASHBOARD ─────────────────────────────────────────────────────────────
  { id: "tpl_dashboard_stats", name: "Stats Dashboard", category: "Dashboard", description: "KPI cards with charts and recent activity", thumbnail: "📊", framework: "both", tags: ["dashboard", "stats", "kpi", "analytics"],
    components: [makeComp("Toolbar", { title: "Dashboard", subtitle: "Good morning, Dr. Irfan" }, 0, 280, 56), makeComp("CardView", { title: "Total Sales: $12,450", subtitle: "+18% this week", icon: "trending_up" }, 68, 130, 72), makeComp("CardView", { title: "Orders: 284", subtitle: "+5 today" }, 68, 130, 72), makeComp("RecyclerView", { orientation: "vertical", adapter: "activity_list" }, 236, 280, 200)] },
  { id: "tpl_dashboard_home", name: "Home Dashboard", category: "Dashboard", description: "Banner + quick actions + feed", thumbnail: "🏠", framework: "both", tags: ["home", "dashboard", "feed"],
    components: [makeComp("Toolbar", { title: "Home", showSearch: "true" }, 0, 280, 56), makeComp("CardView", { title: "Welcome Back!", subtitle: "You have 3 new messages", background: "#1F6FEB" }, 68, 280, 100), makeComp("RecyclerView", { orientation: "horizontal", adapter: "actions_grid" }, 216, 280, 100), makeComp("RecyclerView", { orientation: "vertical", adapter: "activity_feed" }, 364, 280, 200), makeComp("BottomNavigation", { items: "Home,Search,Notifications,Profile" }, 500, 280, 56)] },
  { id: "tpl_admin_panel", name: "Admin Panel", category: "Dashboard", description: "Admin overview with user/system stats", thumbnail: "🛡️", framework: "both", tags: ["admin", "management", "system"],
    components: [makeComp("Toolbar", { title: "Admin Panel", showMenu: "true" }, 0, 280, 56), makeComp("CardView", { title: "Users: 1,240", color: "#3FB950" }, 68, 130, 72), makeComp("CardView", { title: "Active: 98", color: "#58A6FF" }, 68, 130, 72), makeComp("RecyclerView", { orientation: "vertical", adapter: "user_list" }, 236, 280, 240)] },
  { id: "tpl_analytics", name: "Analytics Screen", category: "Dashboard", description: "Charts, graphs, date filter analytics", thumbnail: "📈", framework: "both", tags: ["analytics", "charts", "graphs"],
    components: [makeComp("Toolbar", { title: "Analytics" }, 0, 280, 56), makeComp("Spinner", { items: "Today,This Week,This Month,This Year" }, 68, 240, 44), makeComp("CardView", { title: "Revenue Chart", chartType: "line", height: "200dp" }, 124, 280, 220), makeComp("CardView", { title: "User Growth", chartType: "bar" }, 356, 280, 160)] },
  { id: "tpl_weather", name: "Weather Dashboard", category: "Dashboard", description: "Current weather with 7-day forecast", thumbnail: "🌤️", framework: "both", tags: ["weather", "forecast", "widget"],
    components: [makeComp("CardView", { title: "Karachi, PK", subtitle: "28°C · Partly Cloudy", background: "#1F6FEB", height: "200dp" }, 0, 280, 200), makeComp("RecyclerView", { orientation: "horizontal", adapter: "hourly_forecast", height: "80dp" }, 212, 280, 88), makeComp("RecyclerView", { orientation: "vertical", adapter: "weekly_forecast" }, 312, 280, 260)] },
  { id: "tpl_iot_control", name: "IoT Control Panel", category: "Dashboard", description: "Smart home device control widgets", thumbnail: "🏡", framework: "both", tags: ["iot", "smart home", "controls"],
    components: [makeComp("Toolbar", { title: "Smart Home" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "horizontal", adapter: "rooms" }, 68, 280, 52), makeComp("RecyclerView", { orientation: "vertical", adapter: "devices_grid", spanCount: "2" }, 132, 280, 380), makeComp("BottomNavigation", { items: "Home,Devices,Scenes,Settings" }, 524, 280, 56)] },

  // ── E-COMMERCE ────────────────────────────────────────────────────────────
  { id: "tpl_product_list", name: "Product Listing", category: "E-Commerce", description: "Grid product cards with search & filter", thumbnail: "🛍️", framework: "both", tags: ["shop", "products", "ecommerce", "grid"],
    components: [makeComp("Toolbar", { title: "Shop", showCart: "true", showSearch: "true" }, 0, 280, 56), makeComp("EditText", { hint: "Search products..." }, 68, 280, 44), makeComp("RecyclerView", { orientation: "horizontal", adapter: "categories" }, 124, 280, 48), makeComp("RecyclerView", { orientation: "vertical", adapter: "product_grid", spanCount: "2" }, 184, 280, 340), makeComp("BottomNavigation", { items: "Home,Shop,Cart,Profile" }, 536, 280, 56)] },
  { id: "tpl_product_detail", name: "Product Detail", category: "E-Commerce", description: "Product image gallery, info, add to cart", thumbnail: "📦", framework: "both", tags: ["product", "detail", "cart"],
    components: [makeComp("ImageView", { src: "product_image", height: "250dp" }, 0, 280, 250), makeComp("TextView", { text: "Premium Wireless Headphones", textSize: "18sp", bold: true }, 260, 280, 48), makeComp("TextView", { text: "$129.99", textSize: "22sp", color: "#1F6FEB", bold: true }, 316, 100, 32), makeComp("Button", { text: "Add to Cart" }, 524, 280, 52)] },
  { id: "tpl_cart", name: "Shopping Cart", category: "E-Commerce", description: "Cart items list with total and checkout", thumbnail: "🛒", framework: "both", tags: ["cart", "checkout", "order"],
    components: [makeComp("Toolbar", { title: "My Cart (3 items)" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "vertical", adapter: "cart_items" }, 68, 280, 280), makeComp("CardView", { title: "Total: $264.99" }, 360, 280, 80), makeComp("Button", { text: "Proceed to Checkout" }, 452, 280, 52)] },
  { id: "tpl_checkout", name: "Checkout Screen", category: "E-Commerce", description: "Address, payment, order review", thumbnail: "💳", framework: "both", tags: ["checkout", "payment", "address"],
    components: [makeComp("Toolbar", { title: "Checkout" }, 0, 280, 56), makeComp("CardView", { title: "123 Main St, Karachi" }, 104, 280, 64), makeComp("CardView", { title: "Visa •••• 4242" }, 216, 280, 64), makeComp("Button", { text: "Place Order" }, 364, 280, 52)] },
  { id: "tpl_order_tracking", name: "Order Tracking", category: "E-Commerce", description: "Real-time order status with timeline", thumbnail: "📍", framework: "both", tags: ["order", "tracking", "delivery"],
    components: [makeComp("Toolbar", { title: "Track Order #ORD-2024-001" }, 0, 280, 56), makeComp("CardView", { title: "Estimated: Dec 25", subtitle: "Out for delivery" }, 68, 280, 72), makeComp("MapView", { showDeliveryPin: "true" }, 152, 280, 200), makeComp("RecyclerView", { orientation: "vertical", adapter: "timeline_steps" }, 364, 280, 200)] },
  { id: "tpl_wishlist", name: "Wishlist", category: "E-Commerce", description: "Saved products with move to cart", thumbnail: "❤️", framework: "both", tags: ["wishlist", "saved", "favorites"],
    components: [makeComp("Toolbar", { title: "My Wishlist" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "vertical", adapter: "wishlist_items" }, 68, 280, 440)] },
  { id: "tpl_flash_sale", name: "Flash Sale", category: "E-Commerce", description: "Limited-time offer with countdown timer", thumbnail: "⚡", framework: "both", tags: ["sale", "countdown", "offer"],
    components: [makeComp("CardView", { title: "FLASH SALE", subtitle: "Ends in 02:34:18", background: "#F85149", height: "100dp" }, 0, 280, 100), makeComp("RecyclerView", { orientation: "vertical", adapter: "sale_products", spanCount: "2" }, 112, 280, 400)] },
  { id: "tpl_reviews", name: "Product Reviews", category: "E-Commerce", description: "Rating breakdown with review list", thumbnail: "⭐", framework: "both", tags: ["reviews", "ratings", "comments"],
    components: [makeComp("Toolbar", { title: "Reviews (284)" }, 0, 280, 56), makeComp("CardView", { title: "4.8 ★", subtitle: "Based on 284 reviews", chartType: "rating_bars" }, 68, 280, 160), makeComp("RecyclerView", { orientation: "vertical", adapter: "reviews_list" }, 240, 280, 360)] },

  // ── CHAT ──────────────────────────────────────────────────────────────────
  { id: "tpl_chat_list", name: "Chat List", category: "Chat", description: "Conversation list with avatars, last message", thumbnail: "💬", framework: "both", tags: ["chat", "messages", "inbox"],
    components: [makeComp("Toolbar", { title: "Messages", showSearch: "true" }, 0, 280, 56), makeComp("EditText", { hint: "Search conversations..." }, 68, 280, 44), makeComp("RecyclerView", { orientation: "vertical", adapter: "chat_list" }, 124, 280, 420), makeComp("FloatingActionButton", { icon: "edit" }, 536, 240, 56)] },
  { id: "tpl_chat_screen", name: "Chat Screen", category: "Chat", description: "Full messaging screen with bubbles & input", thumbnail: "💭", framework: "both", tags: ["chat", "messaging", "bubbles"],
    components: [makeComp("Toolbar", { title: "Dr. Irfan", subtitle: "Online", showCall: "true" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "vertical", adapter: "messages" }, 68, 280, 400), makeComp("CardView", { title: "Message Input", showSend: "true" }, 480, 280, 56)] },
  { id: "tpl_group_chat", name: "Group Chat", category: "Chat", description: "Group messaging with member avatars", thumbnail: "👥", framework: "both", tags: ["group", "chat", "team"],
    components: [makeComp("Toolbar", { title: "eSmart Dev Team (5)", showOptions: "true" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "horizontal", adapter: "group_members", height: "48dp" }, 68, 280, 52), makeComp("RecyclerView", { orientation: "vertical", adapter: "group_messages" }, 132, 280, 360), makeComp("CardView", { title: "Message...", showSend: "true" }, 504, 280, 52)] },
  { id: "tpl_video_call", name: "Video Call", category: "Chat", description: "Video call UI with controls", thumbnail: "📹", framework: "both", tags: ["video", "call", "meeting"],
    components: [makeComp("VideoView", { source: "remote_stream", fullscreen: "true" }, 0, 280, 400), makeComp("VideoView", { source: "local_camera", overlay: "true" }, 240, 120, 160), makeComp("CardView", { title: "Controls", showMute: "true", showEnd: "true" }, 420, 280, 64)] },
  { id: "tpl_voice_call", name: "Voice Call", category: "Chat", description: "Audio call screen with speaker/mute", thumbnail: "📞", framework: "both", tags: ["voice", "call", "audio"],
    components: [makeComp("ImageView", { src: "avatar", circular: "true", height: "120dp" }, 80, 120, 120), makeComp("TextView", { text: "Dr. Irfan", textSize: "24sp", bold: true, textAlign: "center" }, 216, 280, 40), makeComp("TextView", { text: "00:02:34", textSize: "18sp", textAlign: "center" }, 264, 280, 32), makeComp("CardView", { title: "Controls", showMute: "true", showSpeaker: "true", showEnd: "true" }, 420, 280, 80)] },

  // ── SOCIAL ────────────────────────────────────────────────────────────────
  { id: "tpl_news_feed", name: "News Feed", category: "Social", description: "Post cards with likes, comments, share", thumbnail: "📰", framework: "both", tags: ["feed", "social", "posts"],
    components: [makeComp("Toolbar", { title: "Feed", showNotification: "true" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "horizontal", adapter: "stories", height: "80dp" }, 68, 280, 88), makeComp("RecyclerView", { orientation: "vertical", adapter: "posts_feed" }, 168, 280, 380)] },
  { id: "tpl_user_profile", name: "User Profile", category: "Social", description: "Profile header, stats, posts grid", thumbnail: "👤", framework: "both", tags: ["profile", "user", "social"],
    components: [makeComp("ImageView", { src: "cover_photo", height: "150dp" }, 0, 280, 150), makeComp("ImageView", { src: "avatar", circular: "true" }, 110, 80, 80), makeComp("TextView", { text: "Dr. Irfan", textSize: "20sp", bold: true }, 204, 240, 32), makeComp("CardView", { title: "Posts: 124  Followers: 1.2K" }, 280, 280, 60), makeComp("Button", { text: "Follow" }, 352, 120, 40), makeComp("RecyclerView", { orientation: "vertical", adapter: "profile_posts", spanCount: "3" }, 404, 280, 200)] },
  { id: "tpl_stories", name: "Stories Screen", category: "Social", description: "Full-screen story viewer with progress", thumbnail: "⭕", framework: "both", tags: ["stories", "instagram", "status"],
    components: [makeComp("ImageView", { src: "story_image", fullscreen: "true" }, 0, 280, 560), makeComp("ProgressBar", { segments: "5", progress: "2" }, 8, 264, 4), makeComp("CardView", { title: "Dr. Irfan · 2m ago", showAvatar: "true" }, 24, 280, 48)] },
  { id: "tpl_explore", name: "Explore Screen", category: "Social", description: "Discover section with trending content", thumbnail: "🔭", framework: "both", tags: ["explore", "discover", "trending"],
    components: [makeComp("Toolbar", { title: "Explore" }, 0, 280, 56), makeComp("EditText", { hint: "Search people, topics..." }, 68, 280, 44), makeComp("RecyclerView", { orientation: "horizontal", adapter: "trending_topics" }, 124, 280, 48), makeComp("RecyclerView", { orientation: "vertical", adapter: "explore_grid", spanCount: "2" }, 184, 280, 380)] },

  // ── MAPS ──────────────────────────────────────────────────────────────────
  { id: "tpl_map_screen", name: "Map Explorer", category: "Maps", description: "Full-screen map with search and pins", thumbnail: "🗺️", framework: "android", tags: ["map", "location", "gps"],
    components: [makeComp("MapView", { showMyLocation: "true", showCompass: "true" }, 0, 280, 480), makeComp("CardView", { title: "Search Location...", showSearch: "true" }, 16, 260, 52), makeComp("FloatingActionButton", { icon: "my_location" }, 420, 240, 56)] },
  { id: "tpl_nearby", name: "Nearby Places", category: "Maps", description: "Map + list of nearby restaurants/services", thumbnail: "📍", framework: "android", tags: ["nearby", "map", "places"],
    components: [makeComp("Toolbar", { title: "Nearby" }, 0, 280, 56), makeComp("MapView", { height: "260dp", showPins: "true" }, 68, 280, 260), makeComp("RecyclerView", { orientation: "vertical", adapter: "places_list" }, 400, 280, 200)] },
  { id: "tpl_route_planner", name: "Route Planner", category: "Maps", description: "A to B route with turn-by-turn directions", thumbnail: "🧭", framework: "android", tags: ["route", "directions", "navigation"],
    components: [makeComp("CardView", { title: "From: Current Location → To: Destination", showSwap: "true" }, 0, 280, 80), makeComp("MapView", { showRoute: "true", height: "320dp" }, 92, 280, 320), makeComp("RecyclerView", { orientation: "vertical", adapter: "turn_by_turn" }, 424, 280, 200)] },

  // ── MEDIA ─────────────────────────────────────────────────────────────────
  { id: "tpl_music_player", name: "Music Player", category: "Media", description: "Album art, controls, progress bar", thumbnail: "🎵", framework: "both", tags: ["music", "player", "audio"],
    components: [makeComp("Toolbar", { title: "Now Playing", transparent: "true" }, 0, 280, 56), makeComp("ImageView", { src: "album_art", circular: "true" }, 68, 240, 240), makeComp("TextView", { text: "Blinding Lights", textSize: "22sp", bold: true }, 320, 280, 36), makeComp("SeekBar", { progress: "60" }, 400, 280, 40), makeComp("CardView", { title: "Controls", showPrev: "true", showPlay: "true", showNext: "true" }, 452, 280, 64)] },
  { id: "tpl_video_player", name: "Video Player", category: "Media", description: "Full-screen video with controls overlay", thumbnail: "🎬", framework: "both", tags: ["video", "player", "media"],
    components: [makeComp("VideoView", { showControls: "true" }, 0, 280, 300), makeComp("SeekBar", { progress: "30" }, 312, 280, 40), makeComp("RecyclerView", { orientation: "vertical", adapter: "related_videos" }, 364, 280, 240)] },
  { id: "tpl_photo_gallery", name: "Photo Gallery", category: "Media", description: "Masonry grid photo gallery", thumbnail: "🖼️", framework: "both", tags: ["gallery", "photos", "grid"],
    components: [makeComp("Toolbar", { title: "Gallery", showSearch: "true" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "horizontal", adapter: "albums" }, 68, 280, 52), makeComp("RecyclerView", { orientation: "vertical", adapter: "photo_grid", spanCount: "3" }, 132, 280, 420)] },
  { id: "tpl_podcast", name: "Podcast Player", category: "Media", description: "Podcast episode list with player bar", thumbnail: "🎙️", framework: "both", tags: ["podcast", "audio", "episodes"],
    components: [makeComp("Toolbar", { title: "Podcasts" }, 0, 280, 56), makeComp("CardView", { title: "Now Playing: Tech Talk EP.24", showMini: "true" }, 68, 280, 72), makeComp("RecyclerView", { orientation: "vertical", adapter: "episodes_list" }, 152, 280, 380)] },

  // ── HEALTH ────────────────────────────────────────────────────────────────
  { id: "tpl_health_dashboard", name: "Health Dashboard", category: "Health", description: "Steps, heart rate, calories overview", thumbnail: "❤️", framework: "both", tags: ["health", "fitness", "steps"],
    components: [makeComp("Toolbar", { title: "Health Today" }, 0, 280, 56), makeComp("CardView", { title: "Steps: 8,240", progress: "82" }, 68, 280, 100), makeComp("CardView", { title: "Heart Rate: 72 bpm" }, 180, 280, 120), makeComp("RecyclerView", { orientation: "vertical", adapter: "activity_log" }, 404, 280, 160)] },
  { id: "tpl_appointment", name: "Book Appointment", category: "Health", description: "Doctor booking with date/time picker", thumbnail: "🏥", framework: "both", tags: ["appointment", "doctor", "booking"],
    components: [makeComp("Toolbar", { title: "Book Appointment" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "vertical", adapter: "doctors_list" }, 132, 280, 180), makeComp("CardView", { title: "Select Date", showCalendar: "true" }, 324, 280, 200), makeComp("Button", { text: "Confirm Appointment" }, 536, 280, 52)] },
  { id: "tpl_medical_record", name: "Medical Records", category: "Health", description: "Patient health records and prescriptions", thumbnail: "📋", framework: "both", tags: ["medical", "records", "prescription"],
    components: [makeComp("Toolbar", { title: "My Health Records" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "horizontal", adapter: "record_categories" }, 68, 280, 52), makeComp("RecyclerView", { orientation: "vertical", adapter: "records_list" }, 132, 280, 440)] },
  { id: "tpl_workout", name: "Workout Tracker", category: "Health", description: "Exercise set/rep tracker with timer", thumbnail: "💪", framework: "both", tags: ["workout", "fitness", "exercise"],
    components: [makeComp("Toolbar", { title: "Chest Day — 6 exercises" }, 0, 280, 56), makeComp("ProgressBar", { progress: "50", label: "3/6 exercises" }, 68, 280, 40), makeComp("RecyclerView", { orientation: "vertical", adapter: "exercise_list" }, 120, 280, 380), makeComp("Button", { text: "Mark Set Complete", showTimer: "true" }, 512, 280, 52)] },

  // ── EDUCATION ─────────────────────────────────────────────────────────────
  { id: "tpl_course_list", name: "Course Listing", category: "Education", description: "Course cards with progress indicators", thumbnail: "📚", framework: "both", tags: ["courses", "education", "learning"],
    components: [makeComp("Toolbar", { title: "Learn", showSearch: "true" }, 0, 280, 56), makeComp("CardView", { title: "Continue: Android Dev", progress: "65" }, 68, 280, 80), makeComp("RecyclerView", { orientation: "vertical", adapter: "courses_list" }, 220, 280, 360)] },
  { id: "tpl_quiz", name: "Quiz Screen", category: "Education", description: "MCQ quiz with timer and progress", thumbnail: "🎯", framework: "both", tags: ["quiz", "mcq", "test"],
    components: [makeComp("ProgressBar", { progress: "40", showText: "Q 4/10" }, 8, 280, 40), makeComp("CardView", { title: "What is the Activity lifecycle method called when visible?" }, 60, 280, 100), makeComp("RadioButton", { text: "onStart()" }, 172, 280, 44), makeComp("RadioButton", { text: "onResume()" }, 224, 280, 44), makeComp("RadioButton", { text: "onVisible()" }, 276, 280, 44), makeComp("Button", { text: "Next Question" }, 392, 280, 52)] },
  { id: "tpl_video_lesson", name: "Video Lesson", category: "Education", description: "Course video player with notes and progress", thumbnail: "🎓", framework: "both", tags: ["video", "lesson", "learning"],
    components: [makeComp("VideoView", { showControls: "true" }, 0, 280, 220), makeComp("TextView", { text: "Lesson 5: Activity Lifecycle", textSize: "16sp", bold: true }, 232, 280, 32), makeComp("ProgressBar", { progress: "35", label: "35% complete" }, 272, 280, 32), makeComp("RecyclerView", { orientation: "vertical", adapter: "notes_list" }, 316, 280, 260)] },
  { id: "tpl_flashcards", name: "Flashcards", category: "Education", description: "Swipe-to-reveal flashcard study mode", thumbnail: "🃏", framework: "both", tags: ["flashcard", "study", "memory"],
    components: [makeComp("TextView", { text: "Card 12 of 50", textSize: "12sp", textAlign: "center" }, 20, 280, 24), makeComp("CardView", { title: "What is MVVM?", subtitle: "Tap to reveal", height: "240dp", flipAnimation: "true" }, 56, 280, 240), makeComp("CardView", { title: "← Skip    Know it ✓", height: "56dp" }, 308, 280, 56)] },

  // ── FINANCE ───────────────────────────────────────────────────────────────
  { id: "tpl_wallet", name: "Digital Wallet", category: "Finance", description: "Balance card, quick actions, transactions", thumbnail: "💰", framework: "both", tags: ["wallet", "finance", "balance"],
    components: [makeComp("Toolbar", { title: "My Wallet" }, 0, 280, 56), makeComp("CardView", { title: "Total Balance: $5,240.00", background: "#1F6FEB", showCard: "true" }, 68, 280, 140), makeComp("RecyclerView", { orientation: "horizontal", adapter: "quick_actions" }, 220, 280, 80), makeComp("RecyclerView", { orientation: "vertical", adapter: "transactions" }, 352, 280, 240)] },
  { id: "tpl_crypto", name: "Crypto Dashboard", category: "Finance", description: "Crypto portfolio with price charts", thumbnail: "₿", framework: "both", tags: ["crypto", "bitcoin", "portfolio"],
    components: [makeComp("Toolbar", { title: "Portfolio" }, 0, 280, 56), makeComp("CardView", { title: "Portfolio: $28,450", change: "+12.4%", chartType: "area" }, 68, 280, 180), makeComp("RecyclerView", { orientation: "vertical", adapter: "crypto_list" }, 260, 280, 340)] },
  { id: "tpl_invoice", name: "Invoice Screen", category: "Finance", description: "Invoice details with payment status", thumbnail: "🧾", framework: "both", tags: ["invoice", "billing", "payment"],
    components: [makeComp("Toolbar", { title: "Invoice #INV-2024-001" }, 0, 280, 56), makeComp("CardView", { title: "Billed To: Dr. Irfan" }, 68, 280, 80), makeComp("RecyclerView", { orientation: "vertical", adapter: "invoice_items" }, 160, 280, 200), makeComp("Button", { text: "Pay Now" }, 464, 280, 52)] },
  { id: "tpl_budget", name: "Budget Tracker", category: "Finance", description: "Monthly budget vs spending with categories", thumbnail: "📊", framework: "both", tags: ["budget", "spending", "finance"],
    components: [makeComp("Toolbar", { title: "Budget — January 2025" }, 0, 280, 56), makeComp("CardView", { title: "Spent: $1,840 / $3,000", chartType: "donut" }, 68, 280, 200), makeComp("RecyclerView", { orientation: "vertical", adapter: "budget_categories" }, 280, 280, 320)] },
  { id: "tpl_stock", name: "Stock Portfolio", category: "Finance", description: "Stock holdings with profit/loss indicators", thumbnail: "📉", framework: "both", tags: ["stocks", "portfolio", "investment"],
    components: [makeComp("Toolbar", { title: "Portfolio — $45,200" }, 0, 280, 56), makeComp("CardView", { title: "Today: +$420 (+0.9%)", chartType: "sparkline" }, 68, 280, 100), makeComp("RecyclerView", { orientation: "vertical", adapter: "holdings_list" }, 180, 280, 380)] },

  // ── SETTINGS ──────────────────────────────────────────────────────────────
  { id: "tpl_settings", name: "Settings Screen", category: "Settings", description: "App settings with sections and toggles", thumbnail: "⚙️", framework: "both", tags: ["settings", "preferences", "toggle"],
    components: [makeComp("Toolbar", { title: "Settings" }, 0, 280, 56), makeComp("CardView", { title: "Profile Information" }, 100, 280, 52), makeComp("Switch", { text: "Dark Mode" }, 252, 280, 48), makeComp("Switch", { text: "Push Notifications" }, 308, 280, 48), makeComp("Switch", { text: "Biometric Login" }, 364, 280, 48), makeComp("Button", { text: "Sign Out", textColor: "#F85149" }, 484, 280, 48)] },
  { id: "tpl_notification_settings", name: "Notification Settings", category: "Settings", description: "Granular notification preferences", thumbnail: "🔔", framework: "both", tags: ["notifications", "settings", "preferences"],
    components: [makeComp("Toolbar", { title: "Notifications" }, 0, 280, 56), makeComp("Switch", { text: "All Notifications", checked: "true" }, 68, 280, 52), makeComp("Switch", { text: "New Messages" }, 164, 280, 48), makeComp("Switch", { text: "Likes & Reactions" }, 368, 280, 48)] },
  { id: "tpl_privacy", name: "Privacy Settings", category: "Settings", description: "Data privacy and permission controls", thumbnail: "🔐", framework: "both", tags: ["privacy", "security", "permissions"],
    components: [makeComp("Toolbar", { title: "Privacy & Security" }, 0, 280, 56), makeComp("Switch", { text: "Two-Factor Authentication" }, 68, 280, 52), makeComp("Switch", { text: "Location Access" }, 128, 280, 52), makeComp("Switch", { text: "Data Sharing" }, 188, 280, 52), makeComp("CardView", { title: "Download My Data" }, 252, 280, 52), makeComp("Button", { text: "Delete Account", textColor: "#F85149" }, 316, 280, 52)] },
  { id: "tpl_theme_picker", name: "Theme Picker", category: "Settings", description: "App theme selection with color preview", thumbnail: "🎨", framework: "both", tags: ["theme", "appearance", "color"],
    components: [makeComp("Toolbar", { title: "Appearance" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "horizontal", adapter: "theme_mode", height: "80dp" }, 68, 280, 88), makeComp("RecyclerView", { orientation: "vertical", adapter: "color_schemes", spanCount: "3" }, 168, 280, 280)] },

  // ── ONBOARDING ────────────────────────────────────────────────────────────
  { id: "tpl_onboarding_1", name: "Onboarding Step 1", category: "Onboarding", description: "Welcome screen with illustration", thumbnail: "👋", framework: "both", tags: ["onboarding", "welcome", "intro"],
    components: [makeComp("ImageView", { src: "onboarding_1", height: "300dp" }, 40, 280, 300), makeComp("TextView", { text: "Build Amazing Apps", textSize: "26sp", bold: true, textAlign: "center" }, 356, 280, 48), makeComp("ProgressBar", { segments: "3", progress: "1" }, 480, 280, 12), makeComp("Button", { text: "Next" }, 504, 280, 52)] },
  { id: "tpl_onboarding_2", name: "Onboarding Step 2", category: "Onboarding", description: "Feature highlight screen", thumbnail: "✨", framework: "both", tags: ["onboarding", "features", "intro"],
    components: [makeComp("ImageView", { src: "onboarding_2", height: "300dp" }, 40, 280, 300), makeComp("TextView", { text: "AI-Powered Coding", textSize: "26sp", bold: true, textAlign: "center" }, 356, 280, 48), makeComp("ProgressBar", { segments: "3", progress: "2" }, 480, 280, 12), makeComp("Button", { text: "Next" }, 504, 280, 52)] },
  { id: "tpl_onboarding_3", name: "Onboarding Step 3", category: "Onboarding", description: "Ready to start CTA screen", thumbnail: "🚀", framework: "both", tags: ["onboarding", "cta", "start"],
    components: [makeComp("ImageView", { src: "onboarding_3", height: "300dp" }, 40, 280, 300), makeComp("TextView", { text: "Deploy in One Click", textSize: "26sp", bold: true, textAlign: "center" }, 356, 280, 48), makeComp("ProgressBar", { segments: "3", progress: "3" }, 480, 280, 12), makeComp("Button", { text: "Get Started" }, 504, 280, 52)] },
  { id: "tpl_empty_state", name: "Empty State", category: "Onboarding", description: "Empty state with action CTA", thumbnail: "📭", framework: "both", tags: ["empty", "state", "placeholder"],
    components: [makeComp("ImageView", { src: "empty_illustration", height: "180dp" }, 80, 240, 180), makeComp("TextView", { text: "No Items Yet", textSize: "20sp", bold: true, textAlign: "center" }, 276, 280, 32), makeComp("Button", { text: "Get Started" }, 380, 200, 52)] },
  { id: "tpl_success", name: "Success Screen", category: "Onboarding", description: "Order/task completion success screen", thumbnail: "✅", framework: "both", tags: ["success", "confirmation", "complete"],
    components: [makeComp("ImageView", { src: "success_icon", height: "120dp" }, 100, 120, 120), makeComp("TextView", { text: "Order Confirmed!", textSize: "24sp", bold: true, textAlign: "center" }, 236, 280, 40), makeComp("TextView", { text: "Your order #ORD-2024-001 has been placed successfully", textAlign: "center" }, 284, 280, 48), makeComp("Button", { text: "Track Order" }, 360, 280, 52), makeComp("Button", { text: "Continue Shopping", background: "transparent" }, 424, 280, 52)] },

  // ── FOOD ──────────────────────────────────────────────────────────────────
  { id: "tpl_food_home", name: "Food Delivery Home", category: "Food", description: "Restaurant listing with banners", thumbnail: "🍔", framework: "both", tags: ["food", "delivery", "restaurant"],
    components: [makeComp("Toolbar", { title: "Deliver to: Karachi", showCart: "true" }, 0, 280, 56), makeComp("EditText", { hint: "Search restaurants..." }, 68, 280, 44), makeComp("RecyclerView", { orientation: "horizontal", adapter: "promo_banners", height: "140dp" }, 124, 280, 148), makeComp("RecyclerView", { orientation: "vertical", adapter: "restaurants_list" }, 376, 280, 240)] },
  { id: "tpl_restaurant_menu", name: "Restaurant Menu", category: "Food", description: "Menu categories with item cards", thumbnail: "🍽️", framework: "both", tags: ["menu", "restaurant", "food"],
    components: [makeComp("ImageView", { src: "restaurant_cover", height: "200dp" }, 0, 280, 200), makeComp("TextView", { text: "Pizza Palace", textSize: "20sp", bold: true }, 212, 280, 32), makeComp("RecyclerView", { orientation: "horizontal", adapter: "menu_categories" }, 288, 280, 48), makeComp("RecyclerView", { orientation: "vertical", adapter: "menu_items" }, 348, 280, 260)] },
  { id: "tpl_food_cart", name: "Food Cart", category: "Food", description: "Food order cart with item customizations", thumbnail: "🧺", framework: "both", tags: ["food", "cart", "order"],
    components: [makeComp("Toolbar", { title: "Your Order" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "vertical", adapter: "food_cart_items" }, 68, 280, 280), makeComp("CardView", { title: "Subtotal: $24.50 | Delivery: $2.00 | Total: $26.50" }, 360, 280, 80), makeComp("Button", { text: "Place Order" }, 452, 280, 52)] },
  { id: "tpl_recipe", name: "Recipe Detail", category: "Food", description: "Recipe steps with ingredients and timer", thumbnail: "👨‍🍳", framework: "both", tags: ["recipe", "cooking", "food"],
    components: [makeComp("ImageView", { src: "food_photo", height: "220dp" }, 0, 280, 220), makeComp("TextView", { text: "Classic Chicken Biryani", textSize: "20sp", bold: true }, 232, 280, 36), makeComp("CardView", { title: "⏱ 45min  👥 4 servings  🔥 680 cal" }, 276, 280, 56), makeComp("RecyclerView", { orientation: "vertical", adapter: "ingredients_steps" }, 344, 280, 280)] },

  // ── TRAVEL ────────────────────────────────────────────────────────────────
  { id: "tpl_hotel_booking", name: "Hotel Booking", category: "Travel", description: "Hotel listing with search and filters", thumbnail: "🏨", framework: "both", tags: ["hotel", "booking", "travel"],
    components: [makeComp("Toolbar", { title: "Find Hotels" }, 0, 280, 56), makeComp("CardView", { title: "Karachi · Dec 25-27 · 2 guests", showSearch: "true" }, 68, 280, 64), makeComp("RecyclerView", { orientation: "vertical", adapter: "hotels_list" }, 200, 280, 380)] },
  { id: "tpl_flight_search", name: "Flight Search", category: "Travel", description: "Flight search results with filters", thumbnail: "✈️", framework: "both", tags: ["flight", "travel", "search"],
    components: [makeComp("Toolbar", { title: "Karachi → Dubai" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "vertical", adapter: "flights_list" }, 124, 280, 440)] },
  { id: "tpl_itinerary", name: "Trip Itinerary", category: "Travel", description: "Day-by-day travel plan timeline", thumbnail: "🗒️", framework: "both", tags: ["itinerary", "trip", "plan"],
    components: [makeComp("Toolbar", { title: "Dubai Trip — 5 Days" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "horizontal", adapter: "days_tabs" }, 68, 280, 48), makeComp("RecyclerView", { orientation: "vertical", adapter: "day_activities" }, 128, 280, 420)] },

  // ── PRODUCTIVITY ──────────────────────────────────────────────────────────
  { id: "tpl_todo_list", name: "To-Do List", category: "Productivity", description: "Task list with completion checkboxes", thumbnail: "✅", framework: "both", tags: ["todo", "tasks", "productivity"],
    components: [makeComp("Toolbar", { title: "My Tasks" }, 0, 280, 56), makeComp("EditText", { hint: "Add a task..." }, 68, 280, 44), makeComp("RecyclerView", { orientation: "vertical", adapter: "tasks_list" }, 124, 280, 380), makeComp("FloatingActionButton", { icon: "add" }, 500, 240, 56)] },
  { id: "tpl_notes", name: "Notes App", category: "Productivity", description: "Notes grid with search and color tags", thumbnail: "📓", framework: "both", tags: ["notes", "memo", "writing"],
    components: [makeComp("Toolbar", { title: "Notes", showSearch: "true" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "vertical", adapter: "notes_grid", spanCount: "2" }, 68, 280, 460), makeComp("FloatingActionButton", { icon: "edit" }, 516, 240, 56)] },
  { id: "tpl_calendar", name: "Calendar View", category: "Productivity", description: "Monthly calendar with events", thumbnail: "📅", framework: "both", tags: ["calendar", "events", "schedule"],
    components: [makeComp("Toolbar", { title: "January 2025", showNavigation: "true" }, 0, 280, 56), makeComp("CardView", { title: "Calendar Grid", height: "300dp", showWeekDays: "true" }, 68, 280, 300), makeComp("RecyclerView", { orientation: "vertical", adapter: "events_list" }, 420, 280, 180)] },
  { id: "tpl_file_manager", name: "File Manager", category: "Productivity", description: "Files and folders browser with grid/list toggle", thumbnail: "📁", framework: "android", tags: ["files", "storage", "manager"],
    components: [makeComp("Toolbar", { title: "Files", showGrid: "true" }, 0, 280, 56), makeComp("EditText", { hint: "Search files..." }, 68, 280, 44), makeComp("RecyclerView", { orientation: "vertical", adapter: "files_list" }, 208, 280, 360)] },
  { id: "tpl_kanban", name: "Kanban Board", category: "Productivity", description: "Project kanban with Todo/Doing/Done columns", thumbnail: "📌", framework: "both", tags: ["kanban", "project", "board"],
    components: [makeComp("Toolbar", { title: "Sprint Board" }, 0, 280, 56), makeComp("RecyclerView", { orientation: "horizontal", adapter: "kanban_columns", height: "520dp" }, 68, 280, 528)] },
  { id: "tpl_time_tracker", name: "Time Tracker", category: "Productivity", description: "Work time tracking with project logs", thumbnail: "⏱️", framework: "both", tags: ["time", "tracker", "work"],
    components: [makeComp("Toolbar", { title: "Time Tracker" }, 0, 280, 56), makeComp("CardView", { title: "Today: 4h 32m", showStopwatch: "true", height: "160dp" }, 68, 280, 160), makeComp("RecyclerView", { orientation: "vertical", adapter: "time_entries" }, 240, 280, 320)] },

  // ── UTILITY ───────────────────────────────────────────────────────────────
  { id: "tpl_search", name: "Search Screen", category: "Utility", description: "Global search with filters and history", thumbnail: "🔍", framework: "both", tags: ["search", "filter", "discover"],
    components: [makeComp("EditText", { hint: "Search...", autofocus: "true" }, 8, 280, 52), makeComp("RecyclerView", { orientation: "horizontal", adapter: "filter_chips" }, 72, 280, 44), makeComp("RecyclerView", { orientation: "vertical", adapter: "search_results" }, 164, 280, 400)] },
  { id: "tpl_splash", name: "Splash Screen", category: "Utility", description: "App launch screen with logo animation", thumbnail: "🚀", framework: "both", tags: ["splash", "launch", "startup"],
    components: [makeComp("ImageView", { src: "app_logo", animate: "scale_in" }, 190, 120, 120), makeComp("TextView", { text: "eSmart World", textSize: "28sp", bold: true, textAlign: "center" }, 330, 280, 40), makeComp("ProgressBar", { indeterminate: "true" }, 440, 60, 8)] },
  { id: "tpl_permissions", name: "Permissions Screen", category: "Utility", description: "App permissions request flow", thumbnail: "🔒", framework: "both", tags: ["permissions", "access", "request"],
    components: [makeComp("TextView", { text: "App Permissions", textSize: "22sp", bold: true }, 60, 280, 40), makeComp("CardView", { title: "📷 Camera — For QR scanning" }, 168, 280, 72), makeComp("CardView", { title: "📍 Location — For map features" }, 252, 280, 72), makeComp("CardView", { title: "🔔 Notifications — For alerts" }, 336, 280, 72), makeComp("Button", { text: "Grant Permissions" }, 420, 280, 52)] },
  { id: "tpl_error_screen", name: "Error Screen", category: "Utility", description: "Network error / server down state", thumbnail: "⚠️", framework: "both", tags: ["error", "offline", "network"],
    components: [makeComp("ImageView", { src: "error_illustration", height: "160dp" }, 80, 200, 160), makeComp("TextView", { text: "Something went wrong", textSize: "20sp", bold: true, textAlign: "center" }, 256, 280, 36), makeComp("TextView", { text: "Check your internet connection and try again", textAlign: "center" }, 300, 280, 48), makeComp("Button", { text: "Try Again" }, 368, 200, 52)] },
  { id: "tpl_qr_scanner", name: "QR Scanner", category: "Utility", description: "Camera-based QR/barcode scanner", thumbnail: "📷", framework: "both", tags: ["qr", "scanner", "camera"],
    components: [makeComp("Toolbar", { title: "Scan QR Code", transparent: "true" }, 0, 280, 56), makeComp("View", { style: "cameraPreview", showOverlay: "true", height: "320dp" }, 68, 280, 320), makeComp("TextView", { text: "Align QR code within the frame", textAlign: "center" }, 400, 280, 32), makeComp("Button", { text: "Enter Code Manually" }, 456, 240, 48)] },

  // ── REACT NATIVE ──────────────────────────────────────────────────────────
  { id: "tpl_rn_tab_nav", name: "Tab Navigation", category: "React Native", description: "Bottom tab navigator with 5 screens", thumbnail: "📱", framework: "react-native", tags: ["navigation", "tabs", "react-native"],
    components: [makeComp("SafeAreaView", { flex: "1" }, 0, 280, 560), makeComp("View", { flex: "1" }, 8, 264, 480), makeComp("View", { style: "tabBar", flexDirection: "row", height: "60" }, 460, 280, 60)] },
  { id: "tpl_rn_drawer", name: "Drawer Navigation", category: "React Native", description: "Side drawer navigation with menu items", thumbnail: "☰", framework: "react-native", tags: ["drawer", "navigation", "menu"],
    components: [makeComp("View", { width: "280dp", background: "#161B22", height: "560dp" }, 0, 280, 560), makeComp("Image", { source: "avatar", circular: "true" }, 24, 64, 64), makeComp("Text", { children: "Dr. Irfan", fontSize: "18", fontWeight: "bold" }, 100, 240, 32), makeComp("FlatList", { data: "menuItems" }, 176, 280, 300)] },
  { id: "tpl_rn_modal", name: "Modal Bottom Sheet", category: "React Native", description: "Animated bottom sheet modal", thumbnail: "⬆️", framework: "react-native", tags: ["modal", "bottom-sheet", "overlay"],
    components: [makeComp("View", { flex: "1", background: "rgba(0,0,0,0.5)" }, 0, 280, 560), makeComp("View", { style: "bottomSheet", borderTopRadius: "16", height: "300dp" }, 260, 280, 300), makeComp("FlatList", { data: "options" }, 328, 280, 200)] },
  { id: "tpl_rn_list_detail", name: "List + Detail", category: "React Native", description: "Master-detail pattern with navigation", thumbnail: "📋", framework: "react-native", tags: ["list", "detail", "navigation"],
    components: [makeComp("SafeAreaView", { flex: "1", background: "#0D1117" }, 0, 280, 560), makeComp("TextInput", { placeholder: "Search...", style: "searchBar" }, 8, 280, 44), makeComp("FlatList", { data: "items", keyExtractor: "id" }, 64, 280, 480)] },
  { id: "tpl_rn_animated_hero", name: "Animated Hero", category: "React Native", description: "Parallax scroll hero with animated header", thumbnail: "🌅", framework: "react-native", tags: ["animation", "hero", "parallax"],
    components: [makeComp("View", { style: "hero", height: "300dp", animated: "true" }, 0, 280, 300), makeComp("Text", { children: "eSmart World", fontSize: "32", fontWeight: "800", animated: "true" }, 120, 280, 56), makeComp("ScrollView", { bounces: "true" }, 200, 280, 360)] },
  { id: "tpl_rn_form", name: "RN Form Screen", category: "React Native", description: "Validated form with keyboard handling", thumbnail: "📝", framework: "react-native", tags: ["form", "input", "validation"],
    components: [makeComp("KeyboardAvoidingView", { behavior: "padding" }, 0, 280, 560), makeComp("Text", { children: "Contact Us", fontSize: "24", fontWeight: "700" }, 32, 280, 40), makeComp("TextInput", { placeholder: "Your Name", style: "input" }, 84, 280, 52), makeComp("TextInput", { placeholder: "Email", keyboardType: "email-address", style: "input" }, 148, 280, 52), makeComp("TextInput", { placeholder: "Message", multiline: "true", style: "textarea" }, 212, 280, 120), makeComp("Pressable", { style: "submitButton" }, 344, 280, 52)] },

  // ── ANDROID NATIVE ────────────────────────────────────────────────────────
  { id: "tpl_android_bottom_sheet", name: "Bottom Sheet Dialog", category: "Android", description: "Material bottom sheet with actions", thumbnail: "⬆️", framework: "android", tags: ["bottom sheet", "dialog", "material"],
    components: [makeComp("View", { background: "rgba(0,0,0,0.4)", fullscreen: "true" }, 0, 280, 560), makeComp("CardView", { height: "260dp", cornerRadius: "16dp", alignBottom: "true" }, 300, 280, 260), makeComp("TextView", { text: "Choose Option", textSize: "18sp", bold: true }, 316, 280, 36), makeComp("RecyclerView", { orientation: "vertical", adapter: "sheet_options" }, 360, 280, 180)] },
  { id: "tpl_android_snackbar", name: "Snackbar UI", category: "Android", description: "Bottom snackbar with action button", thumbnail: "📢", framework: "android", tags: ["snackbar", "toast", "notification"],
    components: [makeComp("RecyclerView", { orientation: "vertical", adapter: "content_list" }, 0, 280, 480), makeComp("CardView", { title: "Item deleted · UNDO", background: "#323232", alignBottom: "true" }, 490, 280, 56)] },
  { id: "tpl_android_chip_group", name: "Chip Group Filter", category: "Android", description: "Material chip group for tag/category filtering", thumbnail: "🏷️", framework: "android", tags: ["chips", "filter", "material"],
    components: [makeComp("Toolbar", { title: "Filter Results" }, 0, 280, 56), makeComp("CardView", { title: "Category Chips", style: "chipGroup" }, 68, 280, 64), makeComp("CardView", { title: "Price Range Chips", style: "chipGroup" }, 144, 280, 64), makeComp("RecyclerView", { orientation: "vertical", adapter: "filtered_results" }, 220, 280, 380)] },
];

export const TEMPLATE_CATEGORIES = [
  "All", "Auth", "Dashboard", "E-Commerce", "Chat", "Social",
  "Maps", "Media", "Health", "Education", "Finance", "Settings",
  "Onboarding", "Food", "Travel", "Productivity", "Utility",
  "React Native", "Android",
];
